server:
  port: 8000

spring:
  application:
    name: teacher-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/online_education?serverTimezone=GMT%2B8

# mybatis-plus 日志打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl